apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root
  annotations:
    argocd.argoproj.io/sync-wave: "3"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  project: default
  source:
    path: apps/
    repoURL: https://github.com/deepali-personal/argo-example.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true